spring.application.name=Table booking
### Database ###
spring.datasource.url=jdbc:postgresql://localhost/postgres
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver