spring.application.name=Table booking
spring.liquibase.enabled=true
### Database ###
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.datasource.url=jdbc:postgresql://localhost/postgres
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver